
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncdoing=UTF-8&serverTimezone=UTC
    username: root
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10